### ISSUE TITLE
inheritance support - missing parent attributes

### ISSUE THREAD

**Issue by cybertriton** [dart-lang/json_serializable#486] opened 2019-05-16 19:04 UTC
File 1: a_response.dart

```dart
import 'package:json_annotation/json_annotation.dart';
part 'a_response.g.dart';
abstract class TypedResponse {
  final String objType; <-- base class has this attribute
  TypedResponse(this.objType);
}

class AResponse extends TypedResponse {
   String name;
  AResponse(this.name) : super('A'); 
  factory AResponse.fromJson(Map<String, dynamic> json) => _$AResponseFromJson(json);
  Map<String, dynamic> toJson() => _$AResponseToJson(this);
}
```

Generated file : a_response.g.dart:

```dart
AResponse _$AResponseFromJson(Map<String, dynamic> json) {
  return AResponse(json['name'] as String);
}

Map<String, dynamic> _$AResponseToJson(AResponse instance) {
  final val = <String, dynamic>{};
  void writeNotNull(String key, dynamic value) {
    if (value != null) {
      val[key] = value;
    }
  }
  writeNotNull('name', instance.name); <-- missing objType from base class
  return val;
}
```

In the pubspec.yaml, using
json_annotation: ^2.0.0

Am I missing something or is this a  bug? Thanks.

**Comment by kevmoo** [comment] 2019-05-16 19:15
There is no constructor argument for `objType`, so it's not generated. This is by design.

**Comment by kevmoo** [comment] 2019-05-16 19:16
Duplicate of https://github.com/dart-lang/json_serializable/issues/274

**Closed by kevmoo** 2019-05-16 19:15 UTC
