### ISSUE TITLE
type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>' in type cast

### ISSUE THREAD

**Issue by HerrNiklasRaab** [dart-lang/json_serializable#351] opened 2018-10-20 14:03 UTC
I get following error, when i want to deserialize an object with a property of type List<> containing another serializeable object. If i change **"ChatMember.fromJson(e as Map<String, dynamic>)"** to **"Map<String, dynamic>.from(e)"** everything works perfect. Can you fix this, is there any workaround possible so i can continue my work?

```
E/flutter (21470): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter (21470): type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>' in type cast
E/flutter (21470): #0      Object._as (dart:core/runtime/libobject_patch.dart:78:25)
E/flutter (21470): #1      _$ChatFromJson.<anonymous closure> (file:///C:/Flutter/src/hapi/lib/datamodels/chat.g.dart:13:56)
E/flutter (21470): #2      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
E/flutter (21470): #3      ListIterable.toList (dart:_internal/iterable.dart:219:19)
E/flutter (21470): #4      _$ChatFromJson (file:///C:/Flutter/src/hapi/lib/datamodels/chat.g.dart:14:13)
E/flutter (21470): #5      new Chat.fromJson (package:hapi/datamodels/chat.dart:22:55)
E/flutter (21470): #6      ChatsModel.getChats.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:hapi/models/chats_model.dart:24:72)
E/flutter (21470): #7      FirestoreHelper.fromListToMap.<anonymous closure> (package:hapi/framework/helper/firestorehelper.dart:8:36)
E/flutter (21470): #8      MapBase._fillMapWithMappedIterable (dart:collection/maps.dart:67:32)
E/flutter (21470): #9      new LinkedHashMap.fromIterable (dart:collection/linked_hash_map.dart:124:13)
E/flutter (21470): #10     FirestoreHelper.fromListToMap (package:hapi/framework/helper/firestorehelper.dart:6:16)
E/flutter (21470): #11     ChatsModel.getChats.<anonymous closure>.<anonymous closure> (package:hapi/models/chats_model.dart:24:31)
E/flutter (21470): #12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
E/flutter (21470): #13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter (21470): #14     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter (21470): #15     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
E/flutter (21470): #16     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
E/flutter (21470): #17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (21470): #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```
```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'chat.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Chat _$ChatFromJson(Map<String, dynamic> json) {
  return Chat(
      members: (json['members'] as List)
          ?.map((e) =>
              e == null ? null : ChatMember.fromJson(e as Map<String, dynamic>))
          ?.toList(),
      memberIds: (json['memberIds'] as List)?.map((e) => e as String)?.toList())
    ..creation = json['creation'] == null
        ? null
        : DateTime.parse(json['creation'] as String)
    ..lastUpdate = json['lastUpdate'] == null
        ? null
        : DateTime.parse(json['lastUpdate'] as String);
}

Map<String, dynamic> _$ChatToJson(Chat instance) => <String, dynamic>{
      'creation': instance.creation?.toIso8601String(),
      'lastUpdate': instance.lastUpdate?.toIso8601String(),
      'members': instance.members,
      'memberIds': instance.memberIds
    };

```

**Comment by HerrNiklasRaab** [comment] 2018-10-20 15:18
Workaround:

```dart

  factory Chat.fromJson(Map<String, dynamic> json) {
    json["members"] = (json['members'] as List)
          ?.map((e) =>
              e == null ? null : Map<String, dynamic>.from(e))
          ?.toList();
     return _$ChatFromJson(json);  
  }
```

**Comment by kevmoo** [comment] 2018-10-20 19:39
Duplicate of https://github.com/flutter/flutter/issues/17417 – I'll try to take a look today...

**Closed by kevmoo** 2018-10-20 19:39 UTC

**Comment by kevmoo** [comment] 2018-10-20 19:42
Actually, it looks like the map is coming from `package:hapi` – not sure what that is.

You can configure your generator to use `anyMap` – see https://pub.dartlang.org/packages/json_serializable under `Build Configuration` – set `any_map: true` and you should be good!

Or change your map generation to create `Map<String, dynamic>` instead of `Map<dynamic, dynamic>`

**Comment by HerrNiklasRaab** [comment] 2018-10-20 21:28
Tried any_map: true. But this didn't changed anything. Only working with the provided workaround.

**Comment by HerrNiklasRaab** [comment] 2018-10-21 14:59
@kevmoo Sorry, for the unclear answer. Setting any_map: true didn't change anything, this did not solved my problem.

**Comment by kevmoo** [comment] 2018-10-21 17:56
If the generated code didn't change at all, then you likely have something wrong with your configuration.

**Comment by ajplumlee33** [comment] 2018-12-24 08:53
I couldn't get any_map to work either.  However, I tried `nullable: false` and that fixed the problem for me

**Comment by DarthWindu** [comment] 2018-12-25 23:04
neither `nullable: false` nor `anyMap: true` worked for me, but the original workaround did.

In my case, I had a Map of another serializable object. My workaround in the `fromJson` method was as follows:

`json["owner"] = Map<String, dynamic>.from(json["owner"]);`

**Comment by lukepighetti** [comment] 2019-02-22 19:50
Running into this now. It's immediately apparent when trying to serialize JSON from firebase for some reaosn.

**Comment by lukepighetti** [comment] 2019-02-22 19:53
```
type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>' in type cast
```

None of these works.

Print statement shows a map coming through.

```dart
      contentRef(schemaKey)
          .child(entryId)
          .once()
          .then((snap) => Entry.fromJson(snap.value.cast<String, dynamic>()));
```

```dart
      contentRef(schemaKey)
          .child(entryId)
          .once()
          .then((snap) => Entry.fromJson(Map.from(snap.value)));
```

```dart
      contentRef(schemaKey).child(entryId).once().then(
          (snap) => Entry.fromJson(Map<String, dynamic>.from(snap.value)));
```


using

```
  firebase_database: ^2.0.1+1
  json_serializable: ^2.0.2
```

**Comment by kevmoo** [comment] 2019-02-24 22:42
See https://github.com/flutter/flutter/issues/17417 – please add a 👍 there to encourage the flutter folks to run on it

**Comment by lukepighetti** [comment] 2019-02-25 01:58
Thanks @kevmoo , I was able to move forward by using `anyMap: true` and switching to `MyClass.toJson(Map json)` instead of `MyClass.toJson(Map<String, dynamic> json)`

**Comment by agueroveraalvaro** [comment] 2019-06-14 23:47
Only this was my solution

        Map data = jsonDecode(result.body);
        List<dynamic> list = List();
        list = data["result"].map((result) => new MyModel.fromJson(result)).toList();

        for(int b=0;b<list.length;b++)
        {
          MyModel myModel = list[b] as MyModel;
          _add(myModel);
        }

**Comment by rv786** [comment] 2019-07-31 20:57
> neither `nullable: false` nor `anyMap: true` worked for me, but the original workaround did.
> 
> In my case, I had a Map of another serializable object. My workaround in the `fromJson` method was as follows:
> 
> `json["owner"] = Map<String, dynamic>.from(json["owner"]);`

The best idea to Fix The Error 
`Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'List<Map<String, dynamic>>' in type cast`
From `jsonDecode("[]") as List<Map<String, dynamic>>` To `List<Map<String, dynamic>>.from(jsonDecode("[]"))`

**Comment by esonchen** [comment] 2019-08-01 02:28
When argument data pass through by MethodChannel or EventChannel. we should use codec **_JSONMethodCodec_** which will ensure type as Map<String, dynamic> automatically.

**Comment by kevmoo** [comment] 2019-08-01 03:41
I think the issue is related to
https://github.com/flutter/flutter/issues/17417#issuecomment-431616591

**Comment by zemunkh** [comment] 2020-08-30 15:14
> Workaround:
> 
> ```dart
>   factory Chat.fromJson(Map<String, dynamic> json) {
>     json["members"] = (json['members'] as List)
>           ?.map((e) =>
>               e == null ? null : Map<String, dynamic>.from(e))
>           ?.toList();
>      return _$ChatFromJson(json);  
>   }
> ```

Thanks, I skipped this answer almost 10 times. You saved my life. Huge appreciate. 👍

**Comment by lukepighetti** [comment] 2021-02-23 02:18
This problem is still apparent and it's very annoying. If you try to unwrap any maps from Realtime Database it falls apart.

**Comment by kevmoo** [comment] 2021-02-23 02:34
https://github.com/FirebaseExtended/flutterfire/issues/833

Was this fixed? There's nothing to do here, sady...

**Comment by lukepighetti** [comment] 2021-02-23 11:28
Just for the sake of my understanding, is there any reason why json_serializeable can't do a `Map<String,dynamic>.from()` when it's expecting a map? Would that resolve the issue?

**Comment by lukepighetti** [comment] 2021-02-23 11:29
Also, it looks like they fixed Firestore and not Realtime Database.

**Comment by lukepighetti** [comment] 2021-02-23 12:06
If I edit the `json_serliazble` code to change `e as Map<String,dynamic>` to `Map<String,dynamic>.from(e)` it works as expected

```dart
_$_FBList _$_$_FBListFromJson(Map<String, dynamic> json) {
  return _$_FBList(
    info: json['info'] == null
        ? null
        : FBListInfo.fromJson(json['info'] as Map<String, dynamic>),
    members: (json['members'] as Map<String, dynamic>)?.map(
      (k, e) => MapEntry(
          k,
          e == null
              ? null
              : FBListMember.fromJson(Map<String, dynamic>.from(e))),
    ),
    items: (json['items'] as Map<String, dynamic>)?.map(
      (k, e) => MapEntry(k,
          e == null ? null : FBListItem.fromJson(Map<String, dynamic>.from(e))),
    ),
  );
}
```

```dart
_$_FBList _$_$_FBListFromJson(Map<String, dynamic> json) {
  return _$_FBList(
    info: json['info'] == null
        ? null
        : FBListInfo.fromJson(json['info'] as Map<String, dynamic>),
    members: (json['members'] as Map<String, dynamic>)?.map(
      (k, e) => MapEntry(k,
          e == null ? null : FBListMember.fromJson(e as Map<String, dynamic>)),
    ),
    items: (json['items'] as Map<String, dynamic>)?.map(
      (k, e) => MapEntry(
          k, e == null ? null : FBListItem.fromJson(e as Map<String, dynamic>)),
    ),
  );
}
```

**Comment by lukepighetti** [comment] 2021-02-23 12:18
I was able to get it to work with a combination of things

`any_map: true`

`FBList.fromJson(Map.from(listPayload))`

and 

`factory FBList.fromJson(Map<String, dynamic> json) => _$FBListFromJson(json);`

But I am still curious to hear your thoughts about the solution above.

**Comment by kevmoo** [comment] 2021-02-23 18:25
Yeah `any_may` is your best bet here.

The problem w/ your proposal is it copies data unnecessarily. I guess we could do a `cast`. But it drives me nuts to create these types of work-arounds for other folks code.

**Comment by lukepighetti** [comment] 2021-02-24 00:00
I'm going to consider this resolved, thanks for the reply.

**Comment by BenjaminFarquhar** [comment] 2021-04-04 20:28
Has `any_map: true` stopped working for anyone else since upgrading to 4.1.0 with Flutter 2?

**Comment by exeptionerror** [comment] 2021-04-12 16:36
[[Solved] Unhandled Exception: InternalLinkedHashMap‘ is not a subtype of type ‘List
](https://fluttercorner.com/unhandled-exception-internallinkedhashmapstring-dynamic-is-not-a-subtype-of/)

**Comment by JanobA99** [comment] 2021-08-18 12:02
> Actually, it looks like the map is coming from `package:hapi` – not sure what that is.
> 
> You can configure your generator to use `anyMap` – see https://pub.dartlang.org/packages/json_serializable under `Build Configuration` – set `any_map: true` and you should be good!
> 
> Or change your map generation to create `Map<String, dynamic>` instead of `Map<dynamic, dynamic>`

thanks bro

**Comment by stanley-shavy** [comment] 2023-02-19 08:21
create UserData class then pass data without the <String, dynamic>
UserData.fromRTDB(Map data)

The data after fetching should be the same cast it to map without the <String, dynamic>
final data = snapshot.value as Map;
      final userI = UserData.fromRTDB(data);
