### ISSUE TITLE
Generic generation error

### ISSUE THREAD

**Issue by xdewnik** [dart-lang/json_serializable#539] opened 2019-09-17 11:33 UTC
I've read all issues and tried to implement them, but i'm getting errors during generation as well. 

Code:

```
`
@JsonSerializable()
class BaseResponse<T>{

  final bool result;
  final bool error;
  final String message;

  @JsonKey(fromJson: _dataFromJson, toJson: _dataToJson)
  final T fieldT;

  BaseResponse(this.result, this.error, this.message, this.fieldT);

  factory BaseResponse.fromJson(Map<String, dynamic> json) => _$BaseResponseFromJson<T>(json);
  

}
`
```

Error:

```
[SEVERE] json_serializable:json_serializable on lib/network/response/BaseResponse.dart (cached):
Error running JsonSerializableGenerator
Could not generate `fromJson` code for `fieldT`.
None of the provided `TypeHelper` instances support the defined type.
package:flutter_app/network/response/BaseResponse.dart:13:11
   ╷
13 │   final T fieldT;
   │           ^^^^^^
   ╵
[SEVERE] Failed after 57ms
pub finished with exit code 1

```

How can i resolve this issue?

**Comment by kevmoo** [comment] 2019-09-29 04:28
I think this is a regression w/ `pkg:analyzer`. Investigating

**Comment by kevmoo** [comment] 2019-09-29 20:40
So it works on analyzer `v0.38.1` and is broken on `v0.38.3` and `v0.38.4`

Also seeing it in tests - https://travis-ci.org/dart-lang/json_serializable/jobs/590931419#L295-L303

@devoncarew @stereotype441 @bwilkerson @scheglov

**Comment by scheglov** [comment] 2019-09-29 22:47
Yes, this is caused by changes in `analyzer`.

1. `FunctionType`s are now structured, and don't have elements. But `DartObject` has `toFunctionValue` that returns the instantiated `ExecutableElement`. So, `json_serializable` should be fixed. IIRC `toFunctionValue` was added in `0.37.3`, so any `0.38.x` will work.
```patch
Index: json_serializable/lib/src/type_helper_ctx.dart
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- json_serializable/lib/src/type_helper_ctx.dart	(revision 0295d1ef7c3eb24dc508f02334ae155ee0278be2)
+++ json_serializable/lib/src/type_helper_ctx.dart	(date 1569796087000)
@@ -106,9 +106,7 @@
     return null;
   }
 
-  final type = objectValue.type as FunctionType;
-
-  final executableElement = type.element as ExecutableElement;
+  final executableElement = objectValue.toFunctionValue();
 
   if (executableElement.parameters.isEmpty ||
       executableElement.parameters.first.isNamed ||
```

2. Unfortunately, we have an error in `analyzer` with resolution of unqualified references to static methods in annotations. So, `DefaultWithToJsonClass` and two other tests fail. See https://github.com/dart-lang/sdk/issues/38641.

**Comment by kevmoo** [comment] 2019-10-09 21:33
Should be fixed at https://github.com/dart-lang/json_serializable/commit/13547e6dee95572541a09ed77e495c06adcbbb08

**Closed by kevmoo** 2019-10-09 21:33 UTC
