### ISSUE TITLE
Library import prefixes are ignored.

### ISSUE THREAD

**Issue by isoos** [dart-lang/json_serializable#586] opened 2020-01-04 17:28 UTC
On `JsonKey`, when the function of `toJson` and `fromJson` uses library prefix (e.g. `import 'x.dart' as x;` `JsonKey(fromJson: x.myFunc)`), the generated code does not include the library prefix (it becomes `myFunc` instead of `x.myFunc`).

Similar thing happens when using an prefix-imported `JsonConverter`.

**Comment by kevmoo** [comment] 2020-01-04 18:04
Duplicate of https://github.com/dart-lang/json_serializable/issues/19

Very much known. just a lot of work to deal with. PRs welcome 😄

**Closed by kevmoo** 2020-01-04 18:04 UTC
