### ISSUE TITLE
build_runner with json_serializable reports failure "Unable to resolve asset ID", though the dependency is not used in generated files

### ISSUE THREAD

**Issue by sir-boformer** [dart-lang/json_serializable#273] opened 2018-07-31 16:41 UTC
``dart:ui`` from Flutter causes "Unable to resolve asset ID". The strange thing is that `dart:ui` is not used in json models and it is not imported in json-related dart files.

The build runs through and generates all the serialization code, but in the end, failure is reported.

```
>flutter packages pub run build_runner build
[INFO] Generating build script...
[INFO] Generating build script completed, took 581ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[WARNING] Throwing away cached asset graph due to Dart SDK update.
[INFO] Cleaning up outputs from previous builds....
[INFO] Cleaning up outputs from previous builds. completed, took 21ms

[INFO] Reading cached asset graph completed, took 230ms

[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 612ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Running build...
[INFO] 2.8s elapsed, 3/130 actions completed.
[SEVERE] json_serializable on lib/common/color.dart:
Unable to resolve asset ID for "dart:ui"
[INFO] 5.0s elapsed, 26/130 actions completed.
[INFO] 6.1s elapsed, 38/130 actions completed.
[INFO] 7.1s elapsed, 38/130 actions completed.
[INFO] 8.2s elapsed, 38/130 actions completed.
[INFO] 9.2s elapsed, 46/130 actions completed.
[INFO] 10.3s elapsed, 47/130 actions completed.
[INFO] 11.9s elapsed, 50/130 actions completed.
[INFO] 15.7s elapsed, 78/130 actions completed.
[INFO] 18.5s elapsed, 116/130 actions completed.
[INFO] Running build completed, took 19.5s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 117ms

[SEVERE] Failed after 19.6s
pub finished with exit code 1
```

Here is the source of `color.dart`. build_runner has nothing to do with this file:

```dart
import 'dart:ui';

class NamedColor {
  final String name;
  final Color value;
  const NamedColor(this.name, this.value);
}

const colors = [
  NamedColor('Red', Color(0xffff0000)),
];

Color parseColor(String hexString) {
  if(!hexString.startsWith('#') || hexString.length != 7) {
    throw new FormatException('invalid color');
  }
  final hex = hexString.substring(1);
  final value = int.parse(hex, radix: 16);
  return Color(0xff000000 + value);
}

String serializeColor(Color color) {
  return '#${_formatColorChannel(color.red)}${_formatColorChannel(color.green)}${_formatColorChannel(color.blue)}';
}

String _formatColorChannel(int value) {
  var hex = value.toRadixString(16);
  while(hex.length < 2) hex = '0' + hex;
  return hex;
}
```

**Comment by kevmoo** [comment] 2018-08-02 22:12
Duplicate of #236 - see the explanation of the issue. To deal with this, you'll have to annotate your use of `Color` from `dart:ui` with toJson and fromJson helpers...

**Closed by kevmoo** 2018-08-02 22:12 UTC

**Comment by sir-boformer** [comment] 2018-08-03 06:41
The thing is, I'm not using `Color` in serialized types, only in my UI layer. In fact, the model is completely separate from my UI layer.

There is no class processed by json_serializable that contains a `dart:ui` import!

**Comment by sir-boformer** [comment] 2018-08-03 07:16
Look at this very simple Flutter example project:

https://github.com/sir-boformer/json_failure

It only contains the default main.dart that is created by Flutter, and a `model.dart` that contains a single serializable class, yet the build still fails:

```
>flutter packages pub run build_runner build

[INFO] Generating build script...
[INFO] Generating build script completed, took 608ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 124ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 426ms

[INFO] Running build...
[INFO] Running build completed, took 20ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 61ms

[SEVERE] json_serializable on lib/main.dart (cached):
Unable to resolve asset ID for "dart:ui"

[SEVERE] Failed after 96ms
pub finished with exit code 1
```

**Comment by kevmoo** [comment] 2018-08-03 18:50
@sir-boformer – you may have to explicitly include only our target files...Let me dig to send you an example..

**Comment by sir-boformer** [comment] 2018-08-29 22:39
@kevmoo Got an example how to do this? I just got stuck, code generation no longer works because of this error.

**Comment by kevmoo** [comment] 2018-08-29 22:45
run `flutter --version` for me...

Also, have you ran `flutter packages upgrade` recently?

**Comment by sir-boformer** [comment] 2018-08-29 22:58
It works again after I got rid of all generated files, but the "unable to resolve asset ID" errors are still there.

I'm running the master channel, last package/flutter upgrade maybe one week ago.
```
Flutter 0.6.1-pre.33 • channel master • https://github.com/flutter/flutter.git
Framework • revision 3ae5ecebea (11 days ago) • 2018-08-19 06:25:00 -0400
Engine • revision 03f8ba51e3
Tools • Dart 2.1.0-dev.0.0.flutter-be6309690f
```

**Comment by kevmoo** [comment] 2018-08-29 23:38
> but the "unable to resolve asset ID" errors are still there.

Yeah, that's going to stick around. The analyzer can see into the `dart:ui` library
