### ISSUE TITLE
Fail to show an error for overridden getters

### ISSUE THREAD

**Issue by samogot** [dart-lang/json_serializable#315] opened 2018-09-18 17:57 UTC
Let's assume I have this code in `test.dart` file:
```dart
import 'package:json_annotation/json_annotation.dart';

part 'test.g.dart';

class A {
  final DateTime startTime;
  final DateTime stopTime;
  A(this.startTime, this.stopTime);
}

class B {
  final List<A> list;
  B(List<A> this.list);
}

@JsonSerializable()
class C extends B {
  C(List<A> list) : super(list);
}
```
I got the following error that leads me what to do:
```
[SEVERE] json_serializable on lib/test.dart:
Error running JsonSerializableGenerator
Could not generate `fromJson` code for `list` because of type `A`.
None of the provided `TypeHelper` instances support the defined type.
package:test_dart2js/test.dart:12:17
  final List<A> list;
                ^^^^
```
If A and B is classes from another library I can't add `fromJson` implementation there, but I can override `list` field and pass implementation with `@JsonKey` annotation. Let's do this
```dart
@JsonSerializable()
class C extends B {
  @override
  @JsonKey(fromJson: _fromJson)
  List<A> get list => super.list;

  C(List<A> list) : super(list);
}

_fromJson(List l) => throw UnimplementedError();
```
Now I got the following error, that gives me nothing to understand what the problem is:
```
[SEVERE] json_serializable on lib/test.dart:

RangeError: Start may not be negative, was -1.
```
the real error should be something like this:
```
[SEVERE] json_serializable on lib/test.dart:
Error running JsonSerializableGenerator
Error with `@JsonKey` on `list`. The `fromJson` function `_fromJson` must have one positional paramater.
package:test_dart2js/test.dart:19:15
  List<A> get list => super.list;
              ^^^^
```
But it throws (https://github.com/dart-lang/source_span/blob/1.4.1/lib/src/file.dart#L304) on trying to output source span (https://github.com/dart-lang/source_gen/blob/v0.9.1/source_gen/lib/src/generator.dart#L54). That happens because `element` is not `null`, but its `nameOffset` is `-1`. I failed to trace back why it's `-1` instead of `329` or something like this, but I assume `analyzer` package might be responsible for this.

I don't think this is an issue of `json_serializable`, but i file it here first, because it is how it can be reproduced.

Some versions that might be helpfull:
```
Dart VM version: 2.1.0-dev.0.0 (Thu Aug 9 10:17:40 2018 +0200) on "linux_x64"
analyzer-0.32.5
json_serializable-1.2.1
source_gen-0.9.1
source_span-1.4.1
```

**Comment by samogot** [comment] 2018-09-18 17:57
CC @jakemac53

**Comment by kevmoo** [comment] 2018-10-03 16:50
Closing this out in favor of https://github.com/dart-lang/source_gen/issues/379 – that's the root issue. I think this is due to how we handle FieldElement instances – not a bug in analyzer.

**Closed by kevmoo** 2018-10-03 16:50 UTC
Labels: Type: bug
