### ISSUE TITLE
Move generated code to a different directory

### ISSUE THREAD

**Issue by SAGARSURI** [dart-lang/json_serializable#661] opened 2020-06-22 04:02 UTC
Is there a way to put the generated files somewhere other than with the "source" files? I would like to put all the .g files into a folder to keep my models by themselves.

**Comment by kevmoo** [comment] 2020-06-22 17:59
Duplicate of https://github.com/dart-lang/json_serializable/issues/347

**Closed by kevmoo** 2020-06-22 17:59 UTC
