### ISSUE TITLE
How to get nested values without writing boilerplate code?

### ISSUE THREAD

**Issue by vlytvyne** [dart-lang/json_serializable#657] opened 2020-06-15 15:56 UTC
Is there a way to avoid writing boilerplate nested classes to get deeply nested values? Having json object like this:

```
{
  name: {
    first: "Taras",
    last: "Shevchenko"
  }
  ...
}
```

To just get first name of the user I'm forced to create another class:

```
class User {
  final UserName name;
  ...
}

class UserName {
  final String first;
  final String last;
}
```

It would be great if It could be written with json pointer syntax like following:

```
class User {
  @JsonKey(name: "name/first")
  final UserName name;
   ...
}
```

**Comment by kevmoo** [comment] 2020-06-15 20:55
Duplicate of https://github.com/dart-lang/json_serializable/issues/490

**Closed by kevmoo** 2020-06-15 20:55 UTC
